CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS quiz;
CREATE SCHEMA IF NOT EXISTS question;
CREATE SCHEMA IF NOT EXISTS notification;
 
GRANT ALL PRIVILEGES ON SCHEMA auth        TO quizapp;
GRANT ALL PRIVILEGES ON SCHEMA quiz        TO quizapp;
GRANT ALL PRIVILEGES ON SCHEMA question    TO quizapp;
GRANT ALL PRIVILEGES ON SCHEMA notification TO quizapp;